config/routes.rb
Rails.application.routes.draw do
  draw(:subapp)

  resources :members
  resources :fan_comments
  resources :reviews
  resources :articles
  resources :authors
  resources :users
  resources :books

  # 第7章
  #resource :config

  # resources :books, constraints: { id: /[0-9]{1,2}/ }

  # constraints(id: /[0-9]{1,2}/) do
  #   resources :books
  #   resources :reviews
  # end

  # resources :books, constraints: TimeConstraint.new

  # resources :books, format: false

  # resources :users, controller: :members

  # resources :reviews, as: :comments

  # namespace :admin do
  #   resources :books
  # end

  # scope module: :admin do
  #   resources :books
  # end

  # resources :reviews do
  #   collection do
  #     get :unapproval
  #   end
  #   member do
  #     get :draft
  #   end
  # end

  # resources :reviews do
  #   get :unapproval, on: :collection
  #   get :draft, on: :member
  # end

  # resources :users, except: [ :show, :destroy ]
  # resources :users, only: [ :index, :new, :create, :edit, :update ]

  # resources :reviews, path_names:  { new: :insert, edit: :revise }

  # resources :books do
  #   resources :reviews
  # end

  # resources :books do
  #   resources :reviews, shallow: true
  # end

  # scope shallow_path: :b do
  #   resources :books do
  #     resources :reviews, shallow: true
  #   end
  # end

  # scope shallow_prefix: :b do
  #   resources :books do
  #     resources :reviews, shallow: true
  #   end
  # end

  # concern :additional do
  #   get :unapproval, on: :collection
  #   get :draft, on: :member
  # end

  # resources :reviews, concerns: :additional
  # resources :users, concerns: :additional

  # match '/details(/:id)' => 'hello#index', via: [ :get, :post ]
  # get '/details(/:id)' => 'hello#index'
  # post '/details(/:id)' => 'hello#index'

  # get 'hello/view'
  # get '/articles(/:category)' => 'articles#index', defaults: { category: 'general', format: 'xml' }
  # get 'blogs/:user_id' => 'blogs#index', constraints: { user_id: /[A-Za-z0-9]{3,7}/ }
  # get 'blogs/:user_id' => 'blogs#index', user_id: /[A-Za-z0-9]{3,7}/
  # get '/blogs/:user_id' => 'common/blogs#list'
  # get 'articles' => 'main#index', as: :top
  # get 'articles/*category/:id' => 'articles#category'
  # get '/books/:id' => redirect('/articles/%{id}')
  # get '/books/:id' => redirect {|p, req| "/articles/#{p[:id].to_i + 10000}" }

  root to: 'hello#list'

  get 'routes/direct'

  direct :support do
    'https://wings.msn.to/'
  end

  direct :root do
    { controller: 'hello', action: 'view', anchor: 'hoge' }
  end

  direct :help do |opts|
    uri = URI.parse('https://wings.msn.to/')
    uri.query = opts.to_query unless opts.empty?
    uri.to_s
  end

  direct :reviewed do |model|
    [ model, anchor: model.status ]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  # # 第4章
  get 'hello/index'
  get 'hello/list'
  get 'view/keyword'
  post 'view/search'
  post 'view/create'
  get 'view/field'
  get 'view/select'
  get 'view/col_select'
  get 'view/group_select'
  get 'view/dat_select'
  get 'view/week_select'
  get 'view/col_radio'
  get 'view/fields_for'
  get 'view/raw'
  get 'view/simple_format'
  get 'view/truncate'
  get 'view/excerpt'
  get 'view/highlight'
  get 'view/conc'
  get 'view/sanitize'
  get 'view/number_to'
  get 'view/link'
  get 'view/urlfor'
  get 'view/new'
  get 'members/login'
  get 'view/linkif'
  get 'login/index'
  get 'login/info'
  get 'view/current'
  get 'view/detail'
  get 'view/mailto'
  get 'view/capture'
  get 'view/helper'
  get 'view/helper2'
  get 'view/helper3'
  get 'view/adopt'
  get 'view/provide'
  get 'view/multi'
  get 'view/relation'
  get 'view/download'
  get 'view/quest'
  get 'view/nest'
  get 'view/local'
  get 'view/partial_layout'
  get 'view/partial_col'
  get 'view/partial_spacer'

  # 第5章
  get 'record/find'
  get 'record/find_by'
  get 'record/find_by_multi'
  get 'record/where'
  get 'record/ph1/:publisher/:price' => 'record#ph1'
  get 'record/not(/:id)' => 'record#not'
  get 'record/excluding'
  get 'record/where_or'
  get 'record/where_tuple'
  get 'record/order'
  get 'record/reorder'
  get 'record/in_order'
  get 'record/select'
  get 'record/select2'
  get 'record/offset'
  get 'record/page(/:id)' => 'record#page'
  get 'record/last'
  get 'record/groupby'
  get 'record/havingby'
  get 'record/where2'
  get 'record/unscope'
  get 'record/unscope2'
  get 'record/none(/:id)' => 'record#none'
  get 'record/pluck'
  get 'record/pick'
  get 'record/exists'
  get 'record/scope'
  get 'record/scope2'
  get 'record/def_scope'
  get 'record/count'
  get 'record/average'
  get 'record/create'
  get 'record/update'
  get 'record/groupby2'
  get 'record/literal_sql'
  get 'record/insert_all'
  get 'record/upsert_all'
  get 'record/update_all'
  get 'record/update_all2'
  get 'record/normalizes'
  get 'record/normalizes2'
  get 'record/del'
  get 'record/destroy_all'
  get 'record/transact'
  get 'record/enum_rec'
  get 'record/enum_scope'
  get 'record/keywd'
  post 'record/keywd_process'
  get 'record/belongs'
  get 'record/hasmany'
  get 'record/hasone'
  get 'record/has_and_belongs'
  get 'record/has_many_through'
  get 'record/cache_counter'
  get 'record/memorize'
  get 'record/show_memo'
  get 'record/create_animals'
  get 'record/show_animals'
  get 'record/create_entries'
  get 'record/delegate_list'
  get 'record/missing'
  get 'record/associated'
  get 'record/assoc_join'
  get 'record/assoc_join2'
  get 'record/assoc_join_left'
  get 'record/assoc_includes'
  get 'record/attr'

  # 第6章
  get 'ctrl/para(/:id)' => 'ctrl#para'
  get 'ctrl/para_array'
  get 'ctrl/req_head'
  get 'ctrl/req_head2'
  get 'ctrl/double_render'
  get 'ctrl/plain_render'
  get 'ctrl/head_sample'
  get 'ctrl/redirect'
  get 'ctrl/file_send'
  get 'ctrl/data_send'
  get 'ctrl/res_head'
  get 'ctrl/expires'
  get 'ctrl/log'
  get 'ctrl/get_xml'
  get 'ctrl/get_json'
  get 'ctrl/download'
  get 'ctrl/cookie'
  post 'ctrl/cookie_rec'
  get 'ctrl/cookie_del'
  get 'ctrl/session_show'
  post 'ctrl/session_rec'
  get 'ctrl/session_del'
  get 'ctrl/index'
  get 'ctrl/index2'
  get 'login/index'
  post 'login/auth'
  get 'login/logout'
  get 'sample/index'
  get 'ctrl/device'
  get 'hello/view'
  get 'ctrl/tokengen'
  get 'ctrl/tokenby'

  # 第10章
  get 'extra/sendmail'
  get 'extra/set_job'
  get 'extra/add_file'
  get 'messages/index'
  get 'messages/:topic' => 'messages#index'

  # 11章
  get 'extra/f_cache'
  get 'extra/share1'
  get 'extra/share2'
  get 'extra/model'
  get 'extra/model2'
  get 'extra/trans'
  get 'ctrl/trans'

  # ルートパラメータ経由でロケールを変更
  # scope "(:locale)", locale: /ja|en|de/ do
  #   resources :books
  #   get 'extra/trans'
  # end

  # match '/:locale' => 'hello#list', via: [ :get ]

  get 'extra/up_file'
  post 'extra/add_file'
end

app/models/fan_comment.rb
class FanComment < ApplicationRecord
end

app/controllers/fan_comments_controller.rb
class FanCommentsController < ApplicationController
  before_action :set_fan_comment, only: %i[ show edit update destroy ]

  # GET /fan_comments or /fan_comments.json
  def index
    @fan_comments = FanComment.all
  end

  # GET /fan_comments/1 or /fan_comments/1.json
  def show
  end

  # GET /fan_comments/new
  def new
    @fan_comment = FanComment.new
  end

  # GET /fan_comments/1/edit
  def edit
  end

  # POST /fan_comments or /fan_comments.json
  def create
    @fan_comment = FanComment.new(fan_comment_params)

    respond_to do |format|
      if @fan_comment.save
        format.html { redirect_to fan_comment_url(@fan_comment), notice: "Fan comment was successfully created." }
        format.json { render :show, status: :created, location: @fan_comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fan_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fan_comments/1 or /fan_comments/1.json
  def update
    respond_to do |format|
      if @fan_comment.update(fan_comment_params)
        format.html { redirect_to fan_comment_url(@fan_comment), notice: "Fan comment was successfully updated." }
        format.json { render :show, status: :ok, location: @fan_comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fan_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fan_comments/1 or /fan_comments/1.json
  def destroy
    @fan_comment.destroy!

    respond_to do |format|
      format.html { redirect_to fan_comments_url, notice: "Fan comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fan_comment
      @fan_comment = FanComment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fan_comment_params
      params.require(:fan_comment).permit(:author_no, :name, :body, :deleted)
    end
end

app/helpers/fan_comments_helper.rb
module FanCommentsHelper
end

app/views/fan_comments/_fan_comment.html.erb
<div id="<%= dom_id fan_comment %>">
  <p>
    <strong>Author no:</strong>
    <%= fan_comment.author_no %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= fan_comment.name %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= fan_comment.body %>
  </p>

  <p>
    <strong>Deleted:</strong>
    <%= fan_comment.deleted %>
  </p>

</div>

app/views/fan_comments/_form.html.erb
<%= form_with(model: fan_comment) do |form| %>
  <% if fan_comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(fan_comment.errors.count, "error") %> prohibited this fan_comment from being saved:</h2>

      <ul>
        <% fan_comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :author_no, style: "display: block" %>
    <%= form.number_field :author_no %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :deleted, style: "display: block" %>
    <%= form.check_box :deleted %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/fan_comments/edit.html.erb
<h1>Editing fan comment</h1>

<%= render "form", fan_comment: @fan_comment %>

<br>

<div>
  <%= link_to "Show this fan comment", @fan_comment %> |
  <%= link_to "Back to fan comments", fan_comments_path %>
</div>

app/views/fan_comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Fan comments</h1>

<div id="fan_comments">
  <% @fan_comments.each do |fan_comment| %>
    <%= render fan_comment %>
    <p>
      <%= link_to "Show this fan comment", fan_comment %>
    </p>
  <% end %>
</div>

<%= link_to "New fan comment", new_fan_comment_path %>

app/views/fan_comments/new.html.erb
<h1>New fan comment</h1>

<%= render "form", fan_comment: @fan_comment %>

<br>

<div>
  <%= link_to "Back to fan comments", fan_comments_path %>
</div>

app/views/fan_comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @fan_comment %>

<div>
  <%= link_to "Edit this fan comment", edit_fan_comment_path(@fan_comment) %> |
  <%= link_to "Back to fan comments", fan_comments_path %>

  <%= button_to "Destroy this fan comment", @fan_comment, method: :delete %>
</div>